name = "cart-uplift"
type = "theme"
handle = "cart-drawer"

[settings]
  [[settings.fields]]
    key = "app_name"
    type = "single_line_text_field"
    name = "App Name"
    default = "Cart Uplift"

  # Cart Behavior Settings - Frequently changed
  [[settings.fields]]
    type = "header"
    content = "🛒 Cart Behavior"

  [[settings.fields]]
    key = "auto_open_cart"
    type = "checkbox"
    name = "Auto-open cart when item added"
    info = "Automatically show cart uplift when customers add items"
    default = true

  [[settings.fields]]
    key = "enable_free_shipping"
    type = "checkbox"
    name = "Show free shipping progress"
    info = "Display progress bar and messages for free shipping threshold"
    default = true

  [[settings.fields]]
    key = "free_shipping_threshold"
    type = "number"
    name = "Free shipping threshold"
    info = "Minimum order amount for free shipping (in shop currency)"
    default = 100

  # Appearance Settings - Most frequently changed
  [[settings.fields]]
    type = "header"
    content = "🎨 Appearance"

  [[settings.fields]]
    key = "button_color"
    type = "color"
    name = "Button & accent color"
    info = "Primary color for buttons and progress bars"
    default = "#000000"

  [[settings.fields]]
    key = "text_color"
    type = "color"
    name = "Text color"
    info = "Main text color in the cart uplift"
    default = "#1A1A1A"

  [[settings.fields]]
    key = "recommendations_background_color"
    type = "color"
    name = "Recommendations background color"
    info = "Background color for the entire recommendations section"
    default = "#ecebe3"

  # Product Recommendations - Commonly adjusted
  [[settings.fields]]
    type = "header"
    content = "📦 Product Recommendations"

  [[settings.fields]]
    key = "enable_recommendations"
    type = "checkbox"
    name = "Enable Product Recommendations"
    info = "Show recommended products in cart"
    default = true

  [[settings.fields]]
    key = "recommendation_layout"
    type = "select"
    name = "Recommendation Layout"
    options = [
      { value = "horizontal", label = "Horizontal Row (Card Style)" },
      { value = "vertical", label = "Vertical Stack" },
      { value = "grid", label = "Grid Layout" }
    ]
    default = "horizontal"

  [[settings.fields]]
    key = "max_recommendations"
    type = "range"
    name = "Max Recommendations"
    min = 2
    max = 8
    step = 1
    default = 6

  [[settings.fields]]
    key = "recommendations_title"
    type = "single_line_text_field"
    name = "Recommendations Title"
    info = "Title shown above recommendations"
    default = "You might also like"

