# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06d17c445a3713f419add1e31894bcc3"
name = "cart-uplift-app"
application_url = "https://final-french-postings-firewall.trycloudflare.com"
embedded = true
handle = "cart-uplift-app-7"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_customers,write_themes,read_themes,write_script_tags,read_script_tags"

[auth]
redirect_urls = ["https://final-french-postings-firewall.trycloudflare.com/auth/callback", "https://final-french-postings-firewall.trycloudflare.com/auth/shopify/callback", "https://final-french-postings-firewall.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://final-french-postings-firewall.trycloudflare.com/apps/proxy"
subpath = "cart-uplift"
prefix = "apps"
