# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06d17c445a3713f419add1e31894bcc3"
name = "cart-uplift-app"
application_url = "https://longer-travel-unknown-wrote.trycloudflare.com"
embedded = true
handle = "cart-uplift-app-7"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_script_tags,read_themes,write_orders,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = ["https://longer-travel-unknown-wrote.trycloudflare.com/auth/callback", "https://longer-travel-unknown-wrote.trycloudflare.com/auth/shopify/callback", "https://longer-travel-unknown-wrote.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://longer-travel-unknown-wrote.trycloudflare.com/apps/proxy"
subpath = "cart-uplift"
prefix = "apps"

[pos]
embedded = false
