-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "isOnline" BOOLEAN NOT NULL DEFAULT false,
    "scope" TEXT,
    "expires" DATETIME,
    "accessToken" TEXT NOT NULL,
    "userId" BIGINT,
    "firstName" TEXT,
    "lastName" TEXT,
    "email" TEXT,
    "accountOwner" BOOLEAN NOT NULL DEFAULT false,
    "locale" TEXT,
    "collaborator" BOOLEAN DEFAULT false,
    "emailVerified" BOOLEAN DEFAULT false
);

-- CreateTable
CREATE TABLE "Settings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "enableApp" BOOLEAN NOT NULL DEFAULT true,
    "enableStickyCart" BOOLEAN NOT NULL DEFAULT true,
    "showOnlyOnCartPage" BOOLEAN NOT NULL DEFAULT false,
    "autoOpenCart" BOOLEAN NOT NULL DEFAULT true,
    "enableFreeShipping" BOOLEAN NOT NULL DEFAULT false,
    "freeShippingThreshold" REAL NOT NULL DEFAULT 100,
    "enableRecommendations" BOOLEAN NOT NULL DEFAULT false,
    "enableAddons" BOOLEAN NOT NULL DEFAULT false,
    "enableDiscountCode" BOOLEAN NOT NULL DEFAULT true,
    "enableNotes" BOOLEAN NOT NULL DEFAULT false,
    "enableExpressCheckout" BOOLEAN NOT NULL DEFAULT true,
    "enableAnalytics" BOOLEAN NOT NULL DEFAULT false,
    "cartPosition" TEXT NOT NULL DEFAULT 'bottom-right',
    "cartIcon" TEXT NOT NULL DEFAULT 'cart',
    "freeShippingText" TEXT NOT NULL DEFAULT 'You''re {{ amount }} away from free shipping!',
    "freeShippingAchievedText" TEXT NOT NULL DEFAULT '🎉 Congratulations! You''ve unlocked free shipping!',
    "recommendationsTitle" TEXT NOT NULL DEFAULT 'You might also like',
    "actionText" TEXT NOT NULL DEFAULT 'Add discount code',
    "addButtonText" TEXT NOT NULL DEFAULT 'Add',
    "checkoutButtonText" TEXT NOT NULL DEFAULT 'CHECKOUT',
    "applyButtonText" TEXT NOT NULL DEFAULT 'Apply',
    "discountLinkText" TEXT NOT NULL DEFAULT '+ Got a promotion code?',
    "notesLinkText" TEXT NOT NULL DEFAULT '+ Add order notes',
    "backgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "textColor" TEXT NOT NULL DEFAULT '#1A1A1A',
    "buttonColor" TEXT NOT NULL DEFAULT '#000000',
    "buttonTextColor" TEXT NOT NULL DEFAULT '#ffffff',
    "recommendationsBackgroundColor" TEXT NOT NULL DEFAULT '#ecebe3',
    "shippingBarBackgroundColor" TEXT NOT NULL DEFAULT '#f0f0f0',
    "shippingBarColor" TEXT NOT NULL DEFAULT '#121212',
    "recommendationLayout" TEXT NOT NULL DEFAULT 'carousel',
    "maxRecommendations" INTEGER NOT NULL DEFAULT 4,
    "complementDetectionMode" TEXT NOT NULL DEFAULT 'automatic',
    "manualRecommendationProducts" TEXT NOT NULL DEFAULT '',
    "stickyCartShowIcon" BOOLEAN NOT NULL DEFAULT true,
    "stickyCartShowCount" BOOLEAN NOT NULL DEFAULT true,
    "stickyCartShowTotal" BOOLEAN NOT NULL DEFAULT true,
    "stickyCartBackgroundColor" TEXT NOT NULL DEFAULT '#000000',
    "stickyCartTextColor" TEXT NOT NULL DEFAULT '#ffffff',
    "stickyCartCountBadgeColor" TEXT NOT NULL DEFAULT '#ff4444',
    "stickyCartCountBadgeTextColor" TEXT NOT NULL DEFAULT '#ffffff',
    "stickyCartBorderRadius" INTEGER NOT NULL DEFAULT 25,
    "progressBarMode" TEXT NOT NULL DEFAULT 'free-shipping',
    "enableGiftGating" BOOLEAN NOT NULL DEFAULT false,
    "giftProgressStyle" TEXT NOT NULL DEFAULT 'single-next',
    "giftThresholds" TEXT NOT NULL DEFAULT '[]',
    "giftNoticeText" TEXT NOT NULL DEFAULT 'Free gift added: {{product}} (worth {{amount}})',
    "giftPriceText" TEXT NOT NULL DEFAULT 'FREE',
    "themeEmbedEnabled" BOOLEAN NOT NULL DEFAULT false,
    "themeEmbedLastSeen" DATETIME,
    "enableEnhancedBundles" BOOLEAN NOT NULL DEFAULT false,
    "showPurchaseCounts" BOOLEAN NOT NULL DEFAULT false,
    "showRecentlyViewed" BOOLEAN NOT NULL DEFAULT false,
    "showTestimonials" BOOLEAN NOT NULL DEFAULT false,
    "showTrustBadges" BOOLEAN NOT NULL DEFAULT false,
    "highlightHighValue" BOOLEAN NOT NULL DEFAULT false,
    "enhancedImages" BOOLEAN NOT NULL DEFAULT false,
    "animatedSavings" BOOLEAN NOT NULL DEFAULT false,
    "highValueThreshold" INTEGER NOT NULL DEFAULT 150,
    "bundlePriority" TEXT NOT NULL DEFAULT 'value',
    "badgeHighValueText" TEXT NOT NULL DEFAULT 'Best Value',
    "badgePopularText" TEXT NOT NULL DEFAULT 'Most Popular',
    "badgeTrendingText" TEXT NOT NULL DEFAULT 'Trending',
    "testimonialsList" TEXT NOT NULL DEFAULT '[]',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Settings_shop_key" ON "Settings"("shop");
